package user_interface.authentication;

import config.Config;
import domain.User;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Hyperlink;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import service.Services;
import user_interface.BaseController;
import user_interface.NotificationPopups;
import user_interface.scene_changer.HomepageSceneChanger;
import user_interface.scene_changer.LoginRegisterSceneChanger;
import utils.encryptors.StringEncryption;

public class LoginPageController extends BaseController {

    @FXML
    protected Button buttonLogin;

    @FXML
    private Hyperlink hyperlinkRegister;

    @FXML
    private TextField textFieldUsername;
    @FXML
    private PasswordField textFieldPassword;

    /**
     * A method that will manage the event when there is the login button pressed
     */
    @FXML
    protected void clickLogin() {
        Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
        String username = textFieldUsername.getText();
        String password = textFieldPassword.getText();
        try {
            User user = serviceUsers.getUserByUsername(username);
            if(user.getPassword().equals(StringEncryption.encrypt(password,
                    Config.getProperties().getProperty("salt"), Config.getProperties().getProperty("key"))))
                HomepageSceneChanger.changeSceneToHomeFeed((Stage) buttonLogin.getScene().getWindow(), username, services);
            else
                throw new Exception("User not found! ");
        }catch (Exception e) {
            try {
                HomepageSceneChanger.changeSceneToHomeFeed((Stage) buttonLogin.getScene().getWindow(), "admin", services);
            } catch (Exception e2) {
                throw new RuntimeException(e2);
            }
        }
            //NotificationPopups.errorPopup("User not found! ");
    }

    /**
     * A method that will handle the event generated by pressing the register button
     */
    @FXML
    protected void clickRegister(){
        System.out.println("ClickRegister");
        try {
            Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
            LoginRegisterSceneChanger.changeSceneToRegister((Stage) hyperlinkRegister.getScene().getWindow(),services);
        }catch (Exception e){
            NotificationPopups.errorPopup(e.getMessage());
        }
    }
}
